const data = [
  {
    id: 1,
    image: "./img/collection1.png",
    title: "Yellow Red",
    description: "Current bid ",
    price: "0.005ETH",
    category: "Art",
  },
  {
    id: 2,
    image: "./img/collection2.png",
    title: "Yellow Red",
    description: "Current bid ",
    price: "0.005ETH",
    category: "Art",
  },
  {
    id: 3,
    image: "./img/collection3.png",
    title: "Yellow Red",
    description: "Current bid ",
    price: "0.005ETH",
    category: "Art",
  },
  {
    id: 4,
    image: "./img/collection4.png",
    title: "Yellow Red",
    description: "Current bid ",
    price: "0.005ETH",
    category: "Art",
  },
  {
    id: 5,
    image: "./img/collection5.png",
    title: "Yellow Red",
    description: "Current bid ",
    price: "0.005ETH",
    category: "Art",
  },
  {
    id: 6,
    image: "./img/collection6.png",
    title: "Yellow Red",
    description: "Current bid ",
    price: "0.005ETH",
    category: "Photography",
  },
  {
    id: 7,
    image: "./img/collection7.png",
    title: "Yellow Red",
    description: "Current bid ",
    price: "0.005ETH",
    category: "Photography",
  },
  {
    id: 8,
    image: "./img/collection8.png",
    title: "Yellow Red",
    description: "Current bid ",
    price: "0.005ETH",
    category: "Photography",
  },
  {
    id: 9,
    image: "./img/collection9.png",
    title: "Yellow Red",
    description: "Current bid ",
    price: "0.005ETH",
    category: "Pattern",
  },
];
export default data;
